--- #YAML:1.0
name: Maypole-Plugin-ColumnGroups
version: 0.2
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: set up column groups in Maypole
license: perl
requires:
  Maypole::Config: 0
  NEXT: 0
  Test::More: 0
provides:
  Maypole::Plugin::ColumnGroups:
    file: lib/Maypole/Plugin/ColumnGroups.pm
    version: 0.2
generated_by: Module::Build version 0.2609
